### ISSUE TITLE
Conditional deployments for different environments

### ISSUE THREAD

**Issue by MatteoGioioso** [lumigo-io/SAR-cloudwatch-alarms-macro#12]
Hello there,

I am trying to deploy and apply the macro only to my prod environment, as my understanding I cannot use `!If` intrinsic function in the transform

```
Transform: [
  "AWS::Serverless-2016-10-31",
  !If [ IsProduction, AddCloudWatchAlarms, "AWS::NoValue" ]
]

Conditions:
  IsProduction: !Equals [ !Ref Environment, prod ]

```

this will produce an error for null key

```
Transform: !If [ 
  IsProduction, 
  [  AddCloudWatchAlarms, "AWS::NoValue" ],  
  "AWS::Serverless-2016-10-31" 
]
```

This second will not even pass the `cfn-lint` validation.

Is there a preferred or working method to achieve this?

**Comment by theburningmonk** [comment]
@MatteoGioioso leave the `Transform` be, you just need to add the `Condition` clause on the SAR:

```yml
AutoDeployMyAwesomeLambdaLayer:
  Condition: IsProduction
  Type: AWS::Serverless::Application
  Properties:
    Location:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/cloudwatch-alarms-macro
      SemanticVersion: <enter latest version>
    Parameters:
      DefaultConfigParamName: <SSM param key for the default config>
      MacroName: <optional, name of the macro>
```

**Comment by MatteoGioioso** [comment]
@theburningmonk hey, thanks for the reply. 
That is actually my current setup, however is still deploying all the alarms since the macro will still run.

As my understanding if that layer is not present the deployment will fail because the `AddCloudWatchAlarms` does not exist. If it exists howerver it will still d

Not sure if I am doing something wrong here.

This is my current setup:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: [
  "AWS::Serverless-2016-10-31",
  AddCloudWatchAlarms
]

Parameters:
  Environment:
    Type: String
    AllowedValues:
      # this is due nodejs not recognising prod as valid NODE_ENV
      - prod
      - stag
      - dev
    ConstraintDescription: invalid environment, only [production, staging, development] are allowed


Conditions:
  IsProduction: !Equals [ !Ref Environment, prod ]

Resources:
 # ...


 SARCloudwatchAlarmsLayer:
    Type: AWS::Serverless::Application
    Condition: IsProduction
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:374852340823:applications/cloudwatch-alarms-macro
        SemanticVersion: 1.0.3
      Parameters:
        DefaultConfigParamName: <name of the parameter>

```
